import Link from 'next/link';
import Icon from '../components/Icon';
import {categories} from '../lib/data';

export default function Home(){return <main>
<section className="hero"><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/><div className="container hero-grid"><div><div className="eyebrow">SAM WEST DISTRIBUTES · WHOLESALE + RETAIL</div><h1>Stock up smart.<br/><em>Shop with confidence.</em></h1><p className="hero-copy">One store for the products homes and businesses use every day. Browse retail quantities or switch to wholesale pricing when you buy more.</p><div className="hero-actions"><Link className="btn btn-primary" href="/catalog">Start shopping <Icon name="arrow" size={18}/></Link><Link className="text-link" href="/catalog">Browse categories</Link></div><div className="trust-row"><span><Icon name="check" size={17}/> Clear pricing</span><span><Icon name="check" size={17}/> Wholesale option</span><span><Icon name="check" size={17}/> Mobile-first</span></div></div><div className="hero-card"><div className="hero-card-top"><span>SHOPPING MODE</span><span className="live-dot">● Ready</span></div><div className="mode-preview"><div><small>Retail</small><strong>Everyday buying</strong><p>Simple unit pricing for home shoppers.</p></div><div><small>Wholesale</small><strong>Business buying</strong><p>Volume pricing for larger orders.</p></div></div><div className="hero-note"><Icon name="box" size={22}/><span>Verified product data only — no fabricated catalogue records.</span></div></div></div></section>
<section className="quick-strip"><div className="container quick-grid"><div><span>01</span><strong>Retail & wholesale</strong><small>One catalogue, two buying modes.</small></div><div><span>02</span><strong>Everyday essentials</strong><small>Built around real household needs.</small></div><div><span>03</span><strong>Clear & simple</strong><small>Fast shopping on every screen.</small></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">SHOP BY DEPARTMENT</div><h2>Everything in one place.</h2></div><Link className="text-link" href="/catalog">View all <Icon name="arrow" size={16}/></Link></div><div className="category-grid">{categories.map(([slug,name,desc],i)=><Link className="category-card" href={`/catalog?category=${slug}`} key={slug}><span className="category-number">0{i+1}</span><span className="category-icon"><Icon name="box" size={24}/></span><strong>{name}</strong><p>{desc}</p><span className="arrow-circle"><Icon name="arrow" size={16}/></span></Link>)}</div></div></section>
<section className="section soft"><div className="container principles"><div><div className="eyebrow">WHY SAM WEST</div><h2>Designed for real shopping.</h2><p>Fast on phones, clear on larger screens, and structured so wholesale and retail customers can use the same catalogue without confusion.</p><Link className="btn btn-dark" href="/catalog">Explore the store <Icon name="arrow" size={17}/></Link></div><div className="principle-list"><div><b>01</b><span><strong>Verified catalogue</strong><small>Product identity stays tied to its authorized source.</small></span></div><div><b>02</b><span><strong>Two price levels</strong><small>Retail and wholesale pricing are kept separate.</small></span></div><div><b>03</b><span><strong>Built to scale</strong><small>Imports, variants, stock and orders have a clear home.</small></span></div></div></div></section>
<section className="cta"><div className="container cta-inner"><div><div className="eyebrow">READY WHEN YOU ARE</div><h2>Browse the catalogue.</h2><p>The storefront is ready for your authorized product data to be imported.</p></div><Link className="btn btn-light" href="/catalog">Open catalogue <Icon name="arrow" size={18}/></Link></div></section>
</main>}